name: Build

on:
  push:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build Windows
        run: dotnet publish --os win

      - name: Build Linux
        run: dotnet publish --os linux

      - name: Upload Windows
        uses: actions/upload-artifact@v4
        with:
          name: win64
          path: ./bin/Release/net8.0/win-x64/publish

      - name: Upload Linux
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ./bin/Release/net8.0/linux-x64/publish
